ANSIBLE_VAULT_PASSWORD_FILE := "./scripts/vault.bash"
ANSIBLE_LOCALHOST_WARNING := False

lint:
	@ANSIBLE_VAULT_PASSWORD_FILE=$(ANSIBLE_VAULT_PASSWORD_FILE) pre-commit run --all-files

check:
	@ANSIBLE_VAULT_PASSWORD_FILE=$(ANSIBLE_VAULT_PASSWORD_FILE) pre-commit run --all-files
	@ANSIBLE_VAULT_PASSWORD_FILE=$(ANSIBLE_VAULT_PASSWORD_FILE) ANSIBLE_LOCALHOST_WARNING=$(ANSIBLE_LOCALHOST_WARNING) ansible-playbook .setup_project.yml --check --diff

commit:
	@ANSIBLE_VAULT_PASSWORD_FILE=$(ANSIBLE_VAULT_PASSWORD_FILE) git commit